language: python
sudo: true
matrix:
  include:
  - python: 3.7
    env: TOXENV=py37
  fast_finish: true
install:
- apt-cache depends python-pycurl
- sudo apt-get install libcurl4-gnutls-dev libgnutls-dev
- sudo apt-get install -y gnutls-bin
- pip install twitter Django wheel -U pip
script:
- python manage.py test
deploy:
  provider: pypi
  user: __token__
  password:
    secure: OVG1WJ93r7Llpzl1nCHyBprtpLMlvJ3vyfOk2heflcfqV34S35x6ab44fsUrFLcX9OB2ciFjn1xwSMwfeRUiwNxTj6w5m2d1Iioam9n5XuOEoLTKclAxqhPOFqmEYrUTs+fTHzICt8DZEKJBRe5O33DiD4gfkbjE2DFY+/Bcuqvtw29EWkzkF0VFJzguHQQPB4PVTO9pvbk498Cd3fCY5mJgblezp+bg6VIACMXgIfufXgQ5e8lWE60oWVvoLmv5fpsOtVRXXF8WGAOdsWigYlFUEwGxIMXKr2dGsVhX28nxwksXkwGpitDaYVekT1XpHsOWBMrqV4j70EkoJhOtd7oyGBC9fRu8g7De5rN/HzeoipeQyqVexOB5FXpC06zIWpXNlA3/tiSBlY1vmKK9Hfdm88xZqQE+7Mz0gJEg8dm2viZuUTWz5/TrC6c6jgC9EnqafPL5DKjMc8YCCJnq5myea64VNJ+N7sP92tqYWTKZXgMiDEEqPusHHpA1qW+zGDg1lB4dS87eF4uB0NktDh7bqTcV2zqu5v7aMddPjlP/CDiblkYesHRRMeG2FUiQUadrIELQOEffhzqE08qbf7eC8kQk0YLiQIdrjWyrN8qaRXS+6PhqL3ZliNk+ZxYo1fy4dJALe1G0EDv6VrhY8yzc3LHfwVHVcITRdtl6MhI=
