# Generated by Django 3.0.2 on 2020-01-11 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterClientOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_consumer_key', models.CharField(default='', max_length=100, verbose_name='Twitter API Key')),
                ('twitter_consumer_secret', models.CharField(default='', max_length=100, verbose_name='Twitter API Secret')),
                ('twitter_access_token', models.CharField(default='', max_length=100, verbose_name='Twitter Acdess Token')),
                ('twitter_token_secret', models.CharField(default='', max_length=100, verbose_name='Twitter Token Secret')),
                ('twitter_user_name', models.CharField(default='', max_length=100, unique=True, verbose_name='Twitter User Name')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'CPSS Twitter Client Setting',
                'verbose_name_plural': 'CPSS Twitter Client Settings',
                'db_table': 'cpss_twitter_settings',
            },
        ),
    ]
